### ISSUE TITLE
Navigating to a URL

### ISSUE THREAD

**Issue by jeffkhull** [vaultec81/3Speak-app#9]
Hi,

I'm new to 3speak and trying to use the app.... I want go to go this URL `https://3speak.tv/openDapp?uri=hive:theycallmedan:speak-vdvwxeha`, but I can't figure out what format it has to be to use the "go to copied URL" function.  What's the right format to paste there?  Thanks!

**Comment by vaultec81** [comment]
The go to copied url is a bit different than what's on the 3speak.tv/openDapp page. Go to copied url formatting atleast for viewing a page is `#/watch/(reflink)`. In the case of `https://3speak.tv/openDapp?uri=hive:theycallmedan:speak-vdvwxeha`, it really opens `#/watch/hive:theycallmedan:speak-vdvwxeha` in the app

**Comment by jeffkhull** [comment]
Works great, thanks!
